version: '3.8'
services:
  mariadb:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025