name: PHP CI with MariaDB

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.drawio'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.drawio'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # This sets the timeout for the entire job to 1 minute
    env:
      PLAYWRIGHT_IMAGE: mcr.microsoft.com/playwright:v1.40.0-jammy

    services:
      mariadb:
        image: mariadb:10.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10
      playwright:
        image: mcr.microsoft.com/playwright:v1.40.0-jammy

    steps:
    - uses: actions/checkout@v4

    - name: Copy Config File
      run: cp config.ini.CI config.ini

    - name: Wait for MariaDB
      run: |
        until mysqladmin ping -h 127.0.0.1 --silent; do
          echo 'waiting for db'
          sleep 1
        done

    - name: Check MariaDB Server Version
      run: mysql -h 127.0.0.1 -u root -e "SELECT VERSION();"

    - name: Check Database Character Set and Collation
      run: mysql -h 127.0.0.1 -u root  -e "SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;"

    - name: Copy Config File
      run: bash e2e/update-app-config.sh

    - name: Utilities Test
      run: php ./unittest/utilities.php

    - name: Setup Test Database
      run: ./e2e/setup-test-db.sh

    - name: Start PHP server
      run: php -S localhost:8000 -t pubroot &

    - name: Install dependencies
      run: docker run --rm --network="host" -v $(pwd):/repo -w /repo/e2e ${{ env.PLAYWRIGHT_IMAGE }} npm ci

    - name: Show Playwright version
      run: docker run --rm --network="host" -v $(pwd):/repo -w /repo/e2e ${{ env.PLAYWRIGHT_IMAGE }} npx playwright --version

    - name: Run Playwright Tests
      run: docker run --rm --network="host" -e CI=true -v $(pwd):/repo -w /repo/e2e ${{ env.PLAYWRIGHT_IMAGE }} npx playwright test

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-artifacts
        path: |
          e2e/playwright-report/
          e2e/test-results/
        retention-days: 3
